### ISSUE TITLE
Final capstone project

### ISSUE THREAD

**Issue by yonas44** [yonas44/Book_an_appointment#17]
### We are a team of five and here is the [Kanban board](https://github.com/yonas44/Book_an_appointment/projects/1) 
These is the team:
- @SelmaNdapanda 
- @adebsa2401 
- @yonas44 
- @ifeanyi305 
- @Ney2 
#### Here is the current status of our Kanban board
![image](https://user-images.githubusercontent.com/72081991/228824135-419904ca-f169-4d62-b7dc-ec26d09286f4.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Met all requirements 👍 

## Optional suggestions
- Consider adding labels to help filter by different types of issues/tasks. Can use labels like front-end or back-end. [OPTIONAL]
- Maybe consider if time you've set to some tasks is realistic. [OTPIONAL]

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
